### ISSUE TITLE
tendrl-glusterd service failure

### ISSUE THREAD

**Issue by fbalak** [Tendrl/gluster-integration#145]
`tendrl-glusterd` service fails at first attempt to start. Needs to be restarted. This happens to me every time I install Tendrl.
Tested with `tendrl-gluster-integration-1.2-02_22_2017_04_38_02.noarch`

`# systemctl status tendrl-glusterd`
● tendrl-glusterd.service - Tendrl Gluster Daemon to Manage gluster tasks
   Loaded: loaded (/usr/lib/systemd/system/tendrl-glusterd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since St 2017-02-22 09:38:34 UTC; 14min ago
  Process: 12123 ExecStart=/usr/bin/tendrl-gluster-integration (code=exited, status=1/FAILURE)
 Main PID: 12123 (code=exited, status=1/FAILURE)

```
úno 22 09:38:34 hostname systemd[1]: tendrl-glusterd.service: main process exited, code=exited, status=1/FAILURE
úno 22 09:38:34 hostname systemd[1]: Unit tendrl-glusterd.service entered failed state.
úno 22 09:38:34 hostname systemd[1]: tendrl-glusterd.service failed.
úno 22 09:38:34 hostname systemd[1]: tendrl-glusterd.service holdoff time over, scheduling restart.
úno 22 09:38:34 hostname systemd[1]: start request repeated too quickly for tendrl-glusterd.service
úno 22 09:38:34 hostname systemd[1]: Failed to start Tendrl Gluster Daemon to Manage gluster tasks.
úno 22 09:38:34 hostname systemd[1]: Unit tendrl-glusterd.service entered failed state.
úno 22 09:38:34 hostname systemd[1]: tendrl-glusterd.service failed.
```

`# journalctl _PID=12123`
```
-- Logs begin at St 2017-02-22 09:23:37 UTC, end at St 2017-02-22 09:45:27 UTC. --
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: No handlers could be found for logger "tendrl.commons.config"
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: Traceback (most recent call last):
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/bin/tendrl-gluster-integration", line 9, in <module>
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: load_entry_point('tendrl-gluster-integration==1.2', 'console_scripts', 'tendrl-gluster-integration')
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: return get_distribution(dist).load_entry_point(group, name)
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: return ep.load()
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: entry = __import__(self.module_name, globals(),globals(), ['__name__'])
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/__init__.py", line 51, in <module>
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: GlusterIntegrationNS()
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/__init__.py", line 49, in __init__
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: super(GlusterIntegrationNS, self).__init__()
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 29, in __init__
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: self.config = ns_obj.objects.Config()
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/objects/config/__init__.py", line 
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: "/etc/tendrl/gluster-integration/gluster-integration.conf.yaml"
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: File "/usr/lib/python2.7/site-packages/tendrl/commons/config.py", line 21, in load_config
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: raise err
úno 22 09:38:34 hostname tendrl-gluster-integration[12123]: tendrl.commons.config.ConfigNotFound: Configuration for module: gluster-integration not found at /et
```

**Comment by r0h4n** [comment]
- You cannot start tendrl-{gluster, ceph}-integration standalone. The config file "gluster-integration.conf.yaml" is injected when a ImportCluster or CreateCluster tendrl API call is completed successfully 

I do not recommend, but you can try copying https://github.com/Tendrl/node-agent/blob/develop/etc/tendrl/node-agent/node-agent.conf.yaml.sample and making appropriate changes to try out the service
