### ISSUE TITLE
Exception shown in the logs when gluster_bridge can't find job queue in etcd

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/gluster-integration#26]
When one configure `gluster_bridge` following [the Install docs](https://github.com/Tendrl/gluster_bridge/blob/master/doc/source/installation.rst) and run `tendrl-gluster-bridge`, the following exception appears in the logs:

```
[manager.py:48 -                 _run() ] [Errno 2] No such file or directory
[manager.py:48 -                 _run() ] [Errno 2] No such file or directory
[rpc.py:96 -                 _run() ] EtcdThread run...
[client.py:521 -                 read() ] Issuing read for key /api_job_queue with args {}
[connectionpool.py:383 -        _make_request() ] "GET /v2/keys/api_job_queue HTTP/1.1" 404 79
[rpc.py:99 -                 _run() ] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tendrl_gluster_bridge-0.1-py2.7.egg/tendrl/gluster_bridge/manager/rpc.py", line 97, in _run
    self._server.run()
  File "/usr/lib/python2.7/site-packages/tendrl_gluster_bridge-0.1-py2.7.egg/tendrl/gluster_bridge/manager/rpc.py", line 50, in run
    self._acceptor()
  File "/usr/lib/python2.7/site-packages/tendrl_gluster_bridge-0.1-py2.7.egg/tendrl/gluster_bridge/manager/rpc.py", line 28, in _acceptor
    jobs = self.client.read("/api_job_queue")
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 536, in read
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 848, in wrapper
    return self._handle_server_response(response)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
EtcdKeyNotFound: Key not found : /api_job_queue

[manager.py:48 -                 _run() ] [Errno 2] No such file or directory
[rpc.py:96 -                 _run() ] EtcdThread run...
[client.py:521 -                 read() ] Issuing read for key /api_job_queue with args {}
[connectionpool.py:383 -        _make_request() ] "GET /v2/keys/api_job_queue HTTP/1.1" 404 79
[rpc.py:99 -                 _run() ] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tendrl_gluster_bridge-0.1-py2.7.egg/tendrl/gluster_bridge/manager/rpc.py", line 97, in _run
    self._server.run()
  File "/usr/lib/python2.7/site-packages/tendrl_gluster_bridge-0.1-py2.7.egg/tendrl/gluster_bridge/manager/rpc.py", line 50, in run
    self._acceptor()
  File "/usr/lib/python2.7/site-packages/tendrl_gluster_bridge-0.1-py2.7.egg/tendrl/gluster_bridge/manager/rpc.py", line 28, in _acceptor
    jobs = self.client.read("/api_job_queue")
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 536, in read
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 848, in wrapper
    return self._handle_server_response(response)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
EtcdKeyNotFound: Key not found : /api_job_queue

[manager.py:48 -                 _run() ] [Errno 2] No such file or directory
[manager.py:195 -             shutdown() ] Signal handler: stopping
```
## Expected behavior

Instead of the exception, `gluster_bridge` should validate the data it's getting from etcd and log the issue properly without raising the exception.

**Comment by r0h4n** [comment]
@GowthamShanmugam is this fixed?

**Comment by GowthamShanmugam** [comment]
@r0h4n PR is in under review

**Comment by sankarshanmukhopadhyay** [comment]
If it is possible, please link to the PR and follow up on the completion of review

**Comment by GowthamShanmugam** [comment]
I have already linked this bug with pull request, i have sent review request also

**Comment by sankarshanmukhopadhyay** [comment]
@mbukatov please confirm if the issue is fixed/persists in latest builds and we can then decide on the state of this issue.
