### ISSUE TITLE
Gluster-integration sync fails when volume is deleted

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#483]
When volume is deleted then gluster sync is failing with exception:

Exception in thread State sync thread:
Traceback (most recent call last):
Nov 15 21:39:36 dhcp43-25 tendrl-gluster-integration: File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py", line 297, in run
raise ex
TypeError: int() argument must be a string or a number, not 'NoneType'

Nov 15 21:39:36 dhcp43-25 journal: 2017-11-15 16:09:36.529451+00:00 - gluster_integration - /usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py:293 - run - ERROR - gluster sds state sync error - TypeError: [{u'function': u'__bootstrap', u'line': 784, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.__bootstrap_inner()'}, {u'function': u'__bootstrap_inner', u'line': 811, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.run()'}, {u'function': u'run', u'line': 250, u'file': u'/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py', u'statement': u'client_connections.sync_volume_connections(volumes)'}, {u'function': u'sync_volume_connections', u'line': 24, u'file': u'/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/client_connections.py', u'statement': u'else int(fetched_brick.client_count)'}]

Need to recheck entire gluster sync and because If volume is deleted at the time of sync then sync i may possible to failing in lot of place

**Comment by GowthamShanmugam** [comment]
The solution which I suggest is when we are collecting or saving volume details we need to check volume delete flag is false, then only we have to proceed further. Problem is when the volume is deleted and it is marked as delete in etcd, But sync is again updating deleted flag as false for the particular volume.

To avoid this when the volume is deleted we have to reduce the ttl interval for that particular volume. And in all the places sync before a load or save volume detail we need to check deleted flag of volume.

What happens the volume created immediately with the same name before ttl delete old volume details?
    So the problem only for wherever we are searching volume using volume name and processing, so we need to check flag there also. Because two volume entries with the same name, so it will cause an issue.

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat @nthomas-redhat @nnDarshan please check this solution, and comment

**Comment by GowthamShanmugam** [comment]
This issue is fixed, i am closing this
