### ISSUE TITLE
Service tendrl-gluster-integration fails when cluster is unmanaged

### ISSUE THREAD

**Issue by fbalak** [Tendrl/gluster-integration#562]
When imported cluster is unmanaged in UI, service `tendrl-gluster-integration` fails on all nodes that were part of the cluster. On all nodes is similar error with Python traceback:
```
# systemctl status tendrl-gluster-integration -l
● tendrl-gluster-integration.service - Tendrl Gluster Daemon to Manage gluster tasks
   Loaded: loaded (/usr/lib/systemd/system/tendrl-gluster-integration.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-02-19 12:00:31 UTC; 47s ago
 Main PID: 18071 (code=exited, status=1/FAILURE)

Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: node_tags = json.loads(NS.node_context.tags)
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: return _default_decoder.decode(s)
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: TypeError: expected string or buffer
Feb 19 12:00:31 fbalak-usm2-gl2 systemd[1]: tendrl-gluster-integration.service: main process exited, code=exited, status=1/FAILURE
Feb 19 12:00:31 fbalak-usm2-gl2 systemd[1]: Stopped Tendrl Gluster Daemon to Manage gluster tasks.
Feb 19 12:00:31 fbalak-usm2-gl2 systemd[1]: Unit tendrl-gluster-integration.service entered failed state.
Feb 19 12:00:31 fbalak-usm2-gl2 systemd[1]: tendrl-gluster-integration.service failed.
```
```
# journalctl -u tendrl-gluster-integration
...
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Finding flows in namespace.tendrl.flows
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Registering flow namespace.tendrl.flows.AuthorizeSshKey
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Registering flow namespace.tendrl.flows.ConfigureMonitoring
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Registering flow namespace.tendrl.flows.ExpandCluster
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Registering flow namespace.tendrl.flows.ImportCluster
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Registering flow namespace.tendrl.flows.SetupSsh
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Registering flow namespace.tendrl.flows.UnmanageCluster
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Setup Tendrl definitions (.yml)for namespace.tendrl
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Validating registered (.py) flows in namespace.tendrl.flows
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Validating defined (.yml) flows in namespace.tendrl.flows
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Validating registered (.py) objects in namespace.tendrl.objects
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Validating defined (.yml) objects in namespace.tendrl.objects
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Setup NodeContext for namespace.tendrl
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Load definitions (.yml) for namespace.tendrl.objects.NodeContext
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Setup TendrlContext for namespace.tendrl
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Load definitions (.yml) for namespace.tendrl.objects.TendrlContext
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: Traceback (most recent call last):
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/bin/tendrl-gluster-integration", line 9, in <module>
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: load_entry_point('tendrl-gluster-integration==1.6.0', 'console_scripts', 'tendrl-gluster
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/manager/__init__.py", 
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: complete.wait(timeout=1)
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/lib64/python2.7/threading.py", line 622, in wait
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: self.__cond.wait(timeout, balancing)
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/lib64/python2.7/threading.py", line 362, in wait
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: _sleep(delay)
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/manager/__init__.py", 
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: node_tags = json.loads(NS.node_context.tags)
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: return _default_decoder.decode(s)
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Feb 19 12:00:31 fbalak-usm2-gl2 tendrl-gluster-integration[18071]: TypeError: expected string or buffer
Feb 19 12:00:31 fbalak-usm2-gl2 systemd[1]: tendrl-gluster-integration.service: main process exited, code=exited, status=1/FAILURE
Feb 19 12:00:31 fbalak-usm2-gl2 systemd[1]: Stopped Tendrl Gluster Daemon to Manage gluster tasks.
Feb 19 12:00:31 fbalak-usm2-gl2 systemd[1]: Unit tendrl-gluster-integration.service entered failed state.
Feb 19 12:00:31 fbalak-usm2-gl2 systemd[1]: tendrl-gluster-integration.service failed.
```

`tendrl-gluster-integration` service should be correctly stopped on all nodes when the cluster is unmanaged.

Tested with:
```
tendrl-ansible-1.5.4-1.el7.centos.noarch
tendrl-api-1.6.0-1.el7.centos.noarch
tendrl-api-httpd-1.6.0-1.el7.centos.noarch
tendrl-commons-1.6.0-1.el7.centos.noarch
tendrl-gluster-integration-1.6.0-1.el7.centos.noarch
tendrl-grafana-plugins-1.6.0-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-monitoring-integration-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.0-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-ui-1.6.0-1.el7.centos.noarch
```

**Comment by ltrilety** [comment]
FYI The issue is not in the un-manage of the cluster the same error can be simulated by simply stopping tendrl-gluster-integration service.

**Comment by r0h4n** [comment]
This is fixed, please verify
