### ISSUE TITLE
While stopping the service tendrl-gluster-integration it throws an exception

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#646]
```
May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: Traceback (most recent call last):
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: File "/usr/bin/tendrl-gluster-integration", line 9, in <module>
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: load_entry_point('tendrl-gluster-integration==1.6.3', 'console_scripts', 'tendrl-gluster-integration')()
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/manager/__init__.py", line 144, in main
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: complete.wait(timeout=1)
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: File "/usr/lib64/python2.7/threading.py", line 622, in wait
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: self.__cond.wait(timeout, balancing)
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: File "/usr/lib64/python2.7/threading.py", line 362, in wait
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: _sleep(delay)
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/manager/__init__.py", line 91, in shutdown
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: node_tags = json.loads(NS.node_context.tags)
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: return _default_decoder.decode(s)
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  May 22 09:46:59 usm1-gl1 tendrl-gluster-integration: TypeError: expected string or buffer
```

Need to be fixed

**Comment by shtripat** [comment]
Closing as required PR merged
