### ISSUE TITLE
KeyError: 'parameters'

### ISSUE THREAD

**Issue by fbalak** [Tendrl/gluster-integration#65]
When launched tendrl-gluster-integration command it continuously prints:
```
ERROR - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/manager/rpc.py", line 161, in _run
    self._server.run()
  File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/manager/rpc.py", line 83, in run
    self._acceptor()
  File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/manager/rpc.py", line 70, in _acceptor
    if "etcd_client" in raw_job['parameters']:
KeyError: 'parameters'
```

**Comment by sankarshanmukhopadhyay** [comment]
I recollect this being worked on. Please update if fixes are available in latest/upcoming build @r0h4n

**Comment by r0h4n** [comment]
This one usually happens when you have a job in the tendrl job queue which is wrongly formatted.

Since the job queue is not writable by end users and is only handled by the API we can close this one

**Comment by fbalak** [comment]
Closing it. If I run again into this problem again I will check format of job in job queue.
