### ISSUE TITLE
Unmanage Cluster results in error

### ISSUE THREAD

**Issue by hosting4power** [Tendrl/gluster-integration#693]
When i try to remove a cluster from Tendrl, using the interface. We get the folowing error:

note: the Cluster is in a down state, and does not excists anymore.

**error:**
Failure in Job 355fe225-6d73-44c1-ad7e-84a28aed28f4 Flow tendrl.flows.UnmanageCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 240, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/unmanage_cluster/__init__.py", line 98, in run exc_traceback) FlowExecutionFailedError: ['Traceback (most recent call last):\n', ' File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/unmanage_cluster/__init__.py", line 59, in run\n super(UnmanageCluster, self).run()\n', ' File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py", line 144, in run\n (atom_fqn, self._defs[\'help\'])\n', 'AtomExecutionFailedError: Atom Execution failed. Error: Error executing pre run function: tendrl.objects.Cluster.atoms.CheckClusterNodesUp for flow: Unmanage a Gluster Cluster\n']
16 Aug 2018 12:27:25
error
Failed pre-run: tendrl.objects.Cluster.atoms.CheckClusterNodesUp for flow: Unmanage a Gluster Cluster
16 Aug 2018 12:27:25
info
Nodes ['bea43879-8d66-4002-8471-cb1d2e6ff589', '076d7218-1c89-4347-8918-a01573130c04', 'd89aafc4-831f-433a-acea-9da2aa2405ec'] are down
16 Aug 2018 12:27:25
info
Checking status of nodes [u'bea43879-8d66-4002-8471-cb1d2e6ff589', u'076d7218-1c89-4347-8918-a01573130c04', u'd89aafc4-831f-433a-acea-9da2aa2405ec']
16 Aug 2018 12:27:25
info
Running UnmanageCluster
16 Aug 2018 12:27:25
info
Starting Job 355fe225-6d73-44c1-ad7e-84a28aed28f4
16 Aug 2018 12:27:25

**Version of Gluster in use:**
glusterfs 3.12.11

**Version of Tendrl and sub-packages:**
carbon-selinux.noarch              1.5.4-2.el7.centos       @tendrl-release
hwinfo.x86_64                      20.2-5.3                 @tendrl-dependencies
libx86emu1.x86_64                  1.1-22.1.2               @tendrl-dependencies
pysmi.noarch                       0.2.1-1.el7.centos       @tendrl-dependencies
pysnmp.noarch                      4.3.10-1.el7.centos      @tendrl-dependencies
python-etcd.noarch                 0.4.5-1                  @tendrl-dependencies
python-maps.noarch                 4.2.0-2.el7.centos       @tendrl-dependencies
python2-pyasn1.noarch              0.3.7-1.el7.centos       @tendrl-dependencies
rubygem-bundler.noarch             1.13.6-1.el7.centos      @tendrl-dependencies
rubygem-etcd.noarch                0.3.0-1.el7.centos       @tendrl-dependencies
rubygem-minitest.noarch            5.9.1-1.el7.centos       @tendrl-dependencies
rubygem-mixlib-log.noarch          1.7.1-1.el7.centos       @tendrl-dependencies
rubygem-puma.x86_64                3.6.0-1.el7.centos       @tendrl-dependencies
tendrl-api.noarch                  1.6.3-7.el7              @tendrl-release
tendrl-api-httpd.noarch            1.6.3-7.el7              @tendrl-release
tendrl-commons.noarch              1.6.3-10.el7             @tendrl-release
tendrl-grafana-plugins.noarch      1.6.3-9.el7              @tendrl-release
tendrl-grafana-selinux.noarch      1.5.4-2.el7.centos       @tendrl-release
tendrl-monitoring-integration.noarch
                                   1.6.3-9.el7              @tendrl-release
tendrl-node-agent.noarch           1.6.3-9.el7              @tendrl-release
tendrl-notifier.noarch             1.6.3-4.el7              @tendrl-release
tendrl-ui.noarch                   1.6.3-8.el7              @tendrl-release

**Comment by shtripat** [comment]
Mark,

The un-manage cluster functionality works for an already imported cluster.
Once you import the cluster in tendrl, all the nodes would be reported as UP if they are reachable and updating details to tendrl server.

Can you please explain the steps followed for importing the gluster cluster (how you setup etc) and then how un-manage is executed.

Looking at the error message I can only make out that the nodes of the cluster are not in running state. We will need more details to debug the issue.
